services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 1433:1433
    volumes:
      - /docker/chat/mssql:/var/opt/mssql
